sudo: false

os:
  - linux

language: node_js

node_js:
  - '10'

cache:
  directories:
    - node_modules

before_script:
  - npm install --global gitbook-cli -ddd
  - npm install gitbook-plugin-todo gitbook-plugin-mermaid-v8 -ddd
  - gitbook install
  - gitbook build

services:
  - docker

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t alicfeng/ts.samego.com:latest -f Dockerfile .
  - docker push alicfeng/ts.samego.com:latest
